name: Generate Icons and Create PR

on:
  workflow_dispatch:
  push:
    branches:
      - main # Adjust as needed

env:
  CARGO_TERM_COLOR: always

jobs:
  generate-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run the script
        run: cd egui-phosphor && cargo run --example create_file

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git checkout -b update-icons
          git add .
          git commit -m "Update icons"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-icons

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update icons"
          branch: update-icons
          title: "Update Icons"
          body: "This PR updates the icons generated by the script."
          labels: ["auto-generated"]
